jobscript: "picas-jobscript.tpl"
cluster: "picas-submit.py"
cluster-status: "picas-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 1
restart-times: 5
local-cores: 1
no-shared-fs: {{cookiecutter.no_shared_fs}}
{%- if cookiecutter.no_shared_fs == false -%}
{%- elif cookiecutter.no_shared_fs == true -%}
default-remote-provider: {{cookiecutter.default_remote_provider}}
default-remote-prefix: {{cookiecutter.default_remote_prefix}}/{{cookiecutter.storage_path}}
{% endif %}
